(()=>{
const API='https://wqbjnczynqaahtwpyvrp.supabase.co/functions/v1/project-api';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
let rememberedId=null;
function extractId(el){if(!el)return null;const vals=[el.dataset&&el.dataset.id,el.dataset&&el.dataset.projectId,el.getAttribute&&el.getAttribute('data-id'),el.getAttribute&&el.getAttribute('data-project-id'),el.getAttribute&&el.getAttribute('onclick'),el.getAttribute&&el.getAttribute('href'),el.id];for(const v of vals){const m=String(v||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(m)return m[0]}return null}
function detailId(){const pc=document.getElementById('pc');if(!pc)return null;const m=(pc.innerHTML||'').match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(m)return m[0];for(const el of pc.querySelectorAll('[data-id],[data-project-id],[onclick],a,button,[id]')){const id=extractId(el);if(id)return id}return rememberedId}
function modal(){let m=document.getElementById('deleteProjectModal');if(m)return m;m=document.createElement('div');m.id='deleteProjectModal';m.style.cssText='display:none;position:fixed;inset:0;z-index:100;background:rgba(16,38,63,.48);align-items:center;justify-content:center;padding:18px';m.innerHTML='<div style="width:min(430px,100%);background:#fff;border:1px solid #c4cdd4;border-radius:5px;box-shadow:0 16px 45px rgba(16,38,63,.22);overflow:hidden"><div style="background:#10263f;color:#fff;padding:17px 20px"><h2 style="margin:0;font:700 19px Georgia,serif">Delete project</h2></div><div style="padding:20px"><p style="margin:0 0 14px;color:#52616f;line-height:1.5">This permanently removes the project and its uploaded media.</p><div style="padding:10px 12px;margin-bottom:16px;border-left:3px solid #b13b32;background:#fff7f6;color:#84342d;font-size:13px">Enter the project\'s 4-digit edit PIN to confirm.</div><input id="deleteProjectPin" inputmode="numeric" maxlength="4" autocomplete="off" aria-label="4-digit project PIN" type="password" style="width:100%;height:46px;box-sizing:border-box;border:1px solid #aab4bd;border-radius:3px;padding:0 12px;text-align:center;letter-spacing:.35em;font-size:20px;font-weight:800"><div id="deleteProjectError" style="min-height:18px;margin:7px 0 0;color:#a4372f;font-size:12px"></div><div style="display:flex;justify-content:flex-end;gap:9px;margin-top:18px"><button id="deleteCancel" type="button" style="height:40px;padding:0 14px;border-radius:3px;border:1px solid #aab4bd;background:#fff;color:#455564;font-weight:750">Cancel</button><button id="deleteConfirm" type="button" style="height:40px;padding:0 14px;border-radius:3px;border:1px solid #a4372f;background:#a4372f;color:#fff;font-weight:750">Delete project</button></div></div></div>';document.body.appendChild(m);
const close=()=>{m.style.display='none';document.getElementById('deleteProjectPin').value='';document.getElementById('deleteProjectError').textContent='';document.getElementById('deleteConfirm').disabled=false};
document.getElementById('deleteCancel').onclick=close;m.addEventListener('click',e=>{if(e.target===m)close()});
const input=document.getElementById('deleteProjectPin'),confirm=document.getElementById('deleteConfirm'),err=document.getElementById('deleteProjectError');
input.addEventListener('input',()=>{input.value=input.value.replace(/\D/g,'').slice(0,4);err.textContent=''});input.addEventListener('keydown',e=>{if(e.key==='Enter')confirm.click()});
confirm.onclick=async()=>{const id=m.dataset.projectId,pin=input.value.trim();if(!UUID.test(id||'')){err.textContent='Could not identify this project.';return}if(!/^\d{4}$/.test(pin)){err.textContent='PIN must be exactly 4 digits.';return}confirm.disabled=true;err.textContent='Deleting…';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id,pin})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Could not delete project');location.href='/'}catch(e){confirm.disabled=false;err.textContent=e.message||'Could not delete project.'}};
return m}
function openDelete(id){const m=modal();m.dataset.projectId=id;m.style.display='flex';setTimeout(()=>document.getElementById('deleteProjectPin').focus(),30)}
function install(){const pc=document.getElementById('pc');if(!pc)return;const id=detailId();if(!id)return;const area=pc.querySelector('.edit-area')||pc;let b=area.querySelector('[data-delete-project]');if(!b){b=document.createElement('button');b.type='button';b.dataset.deleteProject='true';b.dataset.projectId=id;b.textContent='Delete Project';b.style.cssText='margin:14px 6px 0;padding:8px 12px;border:1px solid #c58b86;background:#fff;color:#9c3027;border-radius:3px;font-weight:750;cursor:pointer';b.onmouseenter=()=>b.style.background='#fff7f6';b.onmouseleave=()=>b.style.background='#fff';b.onclick=e=>{e.stopPropagation();openDelete(b.dataset.projectId)};area.appendChild(b)}else b.dataset.projectId=id}
document.addEventListener('click',e=>{const el=e.target.closest&&e.target.closest('button,a,[data-id],[data-project-id]');if(!el)return;const id=extractId(el);const text=(el.textContent||'').trim().toLowerCase();if(id&&(el.matches('.view,.edit')||text.includes('view')||text.includes('edit')))rememberedId=id});
new MutationObserver(install).observe(document.documentElement,{subtree:true,childList:true});modal();install();setTimeout(install,250);setTimeout(install,1000);
})();
